### ISSUE TITLE
what about wildcards for extensions?

### ISSUE THREAD

**Issue by tristan-k** [agilecreativity/filename_cleaner#1]
Is there a way to run filename_cleaner on all files without specifying a extension? I tried it with an asterisk

```
filename_cleaner --base-dir . -e * --recursive --sep-char _
```

**Comment by agilecreativity** [comment]
Hi @tristan-k 

I really want to be explicit about what I am renaming to avoid any surprise as this may be too dangerous in some situation. e.g. If you really like to know what are all of the extension you have to deal with I have one more gem that will list all extension call [extension_lister](https://github.com/agilecreativity/extension_lister) that I normally used to list all of the extensions from a given directory:

``` sh
# sample usage
$cd ~/codes/filename_cleaner
$gem install extension_lister
$rbenv rehash # I am using rbenv
$extension_lister
```

You should see something like

```
.gem
.gemspec
.lock
.md
.rb
```

This will list all of the extensions under a given directory that you can use as the parameter to this gem.

e.g. `-e ext1 ext2 ext3`

You are more than welcome to create a PR if you really like to use this feature inside this gem.
